sc: myStack.o proj5Base.o
	   g++ -o sc myStack.o proj5Base.o 
	   
myStack.o: myStack.cpp myStack.h
		g++ -c myStack.cpp	   
	   
proj5Base.o: proj5Base.cpp myStack.h
	   g++ -c proj5Base.cpp
	  	  
		  