proj7: mmart233Proj7.o Island7.o
	   g++ -o proj7 mmart233Proj7.o Island7.o
	   
mmart233Proj7.o: mmart233Proj7.cpp Island7.h
		g++ -c mmart233Proj7.cpp
		
Island7.o: Island7.cpp Island7.h
		g++ -c Island7.cpp
		

	